{
 "title": "Plantilla",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "buckets",
    "query": "import \"influxdata/influxdb/schema\"\n\nbuckets()"
   },
   {
    "name": "cultivos",
    "query": "import \"influxdata/influxdb/schema\"\n\nimport \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n    bucket: \"Tester\",\n    tag: \"planta\",\n    measurement: \"temperatura\",\n)"
   },
   {
    "name": "fincas",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n    bucket: \"Tester\",\n    tag: \"finca\",\n    measurement: \"temperatura\",\n)"
   },
   {
    "name": "fincas2",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n    bucket: \"Tester\",\n    tag: \"finca\",\n    measurement: \"temperatura\",\n)"
   },
   {
    "name": "medidas",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurements(bucket: \"Tester\")"
   },
   {
    "name": "usuarios",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n    bucket: \"Tester\",\n    tag: \"usuario\",\n    measurement: \"temperatura\",\n)"
   },
   {
    "name": "sensor",
    "query": "import \"influxdata/influxdb/schema\" \r\n\r\nschema.tagValues( \r\n  bucket: \"Tester\", \r\n  tag: \"id_sensor\",\r\n  predicate: (r) => r[\"_measurement\"] == \"${medidas}\" and \r\n  r[\"planta\"] == \"${cultivos}\" and \r\n  r[\"finca\"] == \"${fincas}\" and \r\n  r[\"usuario\"] == \"${usuarios}\", \r\n  start: -30d \r\n)"
   },
   {
    "name": "sensor2",
    "query": "import \"influxdata/influxdb/schema\" \r\n\r\nschema.tagValues( \r\n  bucket: \"Tester\", \r\n  tag: \"id_sensor\",\r\n  predicate: (r) => r[\"_measurement\"] == \"${medidas}\" and \r\n  r[\"planta\"] == \"${cultivos}\" and \r\n  r[\"finca\"] == \"${fincas}\" and \r\n  r[\"usuario\"] == \"${usuarios}\", \r\n  start: -30d \r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Reporte",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Tester\") \r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperatura\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\") \r\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\") \r\n  |> filter(fn: (r) => r[\"planta\"] == \"${cultivos}\") \r\n  |> group(columns: [\"finca\"], mode:\"by\") \r\n  |> mean(column: \"_value\")"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"Tester\") \r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"precipitacion\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\") \r\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\") \r\n  |> filter(fn: (r) => r[\"planta\"] == \"${cultivos}\") \r\n  |> group(columns: [\"finca\"], mode:\"by\") \r\n  |> mean(column: \"_value\")"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"Tester\") \r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humedad\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\") \r\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\") \r\n  |> filter(fn: (r) => r[\"planta\"] == \"${cultivos}\") \r\n  |> group(columns: [\"finca\"], mode:\"by\") \r\n  |> mean(column: \"_value\")"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "from(bucket: \"Tester\") \r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"uv\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\") \r\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\") \r\n  |> filter(fn: (r) => r[\"planta\"] == \"${cultivos}\") \r\n  |> group(columns: [\"finca\"], mode:\"by\") \r\n  |> mean(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Modifier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Movil",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Estado del Cultivo en la finca ${fincas}",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"Tester\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  \r\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\r\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\r\n  |> filter(fn: (r) => r[\"planta\"] == \"${cultivos}\")\r\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\r\n  |> group(columns: [\"_measurement\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Registro Histórico - Temperatura",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Tester\")\n  |> range(start: -30d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperatura\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Registro Histórico - Precipitacion",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "targets": [
    {
     "query": "from(bucket: \"Tester\")\n  |> range(start: -30d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"precipitacion\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Registro Histórico - Humedad",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"Tester\")\n  |> range(start: -30d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humedad\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Registro Histórico - Radiación Solar",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "from(bucket: \"Tester\")\n  |> range(start: -30d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"radiacion\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Registro Histórico - Temperatura - ${sensor}",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Registro Histórico - Precipitacion - ${sensor}",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Registro Histórico - Humedad - ${sensor}",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Registro Histórico - Radiación Solar - ${sensor}",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"radiacion\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mapa",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mapa de sensores  en ${fincas}",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "valueName": "current",
   "targets": [
    {
     "measurement": "/^$cultivos$/",
     "query": "from(bucket: \"Tester\")\n  |> range(start: -30d, stop: now())\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"id_sensor\",\"latitud\",\"longitud\"], mode:\"by\")\n  |> mean(column: \"valor\")\n  |> rename(columns: {valor: \"metrica\", id_sensor: \"name\"})\n\n",
     "select": [
      [
       { "params": [ "/^$medidas$/" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mapa de sensores  en ${fincas} - ${medidas}",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "measurement": "/^$cultivos$/",
     "query": "from(bucket: \"Tester\")\n  |> range(start: -30d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${medidas}\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\" and \n  r[\"planta\"] == \"${cultivos}\" and\n  r[\"finca\"] == \"${fincas}\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [\"id_sensor\",\"latitud\",\"longitud\"], mode:\"by\")\n  |> mean(column: \"valor\")\n  |> rename(columns: {valor: \"metrica\", id_sensor: \"name\", latitud: \"latitud\", longitud:\"longitud\"})\n  \n  \n  \n",
     "select": [
      [
       { "params": [ "/^$medidas$/" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pruebas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${medidas} - Comparación",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${medidas}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"planta\"] == \"${cultivos}\")\n  |> filter(fn: (r) =>  r[\"finca\"] == \"${fincas}\" or \n  r[\"finca\"] == \"${fincas2}\")\n  |> group(columns: [\"finca\"], mode:\"by\")\n  |> mean(column: \"_value\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "${medidas} - Comparación",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${medidas}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> filter(fn: (r) => r[\"planta\"] == \"${cultivos}\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"id_sensor\"] == \"${sensor}\" or\n  r[\"id_sensor\"] == \"${sensor2}\")\n  |> group(columns: [\"id_sensor\"], mode:\"by\")\n  |> mean(column: \"_value\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "UV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"radiacion\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"radiacion\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> group(columns: [\"_measurement\"], mode: \"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"radiacion\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"id_sensor\"] == \"${sensor}\" or  r[\"id_sensor\"] =~ /Nodo[0-4]$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"radiacion\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> filter(fn: (r) => r[\"id_sensor\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"planta\"] == \"${cultivos}\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> group(columns: [\"_measurement\"], mode: \"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperatura\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperatura\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> group(columns: [\"_measurement\"], mode: \"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperatura\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"id_sensor\"] == \"${sensor}\" or  r[\"id_sensor\"] =~ /Nodo[0-4]$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperatura\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> filter(fn: (r) => r[\"id_sensor\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"planta\"] == \"${cultivos}\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> group(columns: [\"_measurement\"], mode: \"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Precipitacion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"precipitacion\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"precipitacion\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> group(columns: [\"_measurement\"], mode: \"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"precipitacion\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"id_sensor\"] == \"${sensor}\" or  r[\"id_sensor\"] =~ /Nodo[0-4]$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"precipitacion\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> filter(fn: (r) => r[\"id_sensor\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"planta\"] == \"${cultivos}\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> group(columns: [\"_measurement\"], mode: \"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humedad\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humedad\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> group(columns: [\"_measurement\"], mode: \"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humedad\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> filter(fn: (r) => r[\"id_sensor\"] == \"${sensor}\" or  r[\"id_sensor\"] =~ /Nodo[0-4]$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"Tester\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humedad\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valor\")\n  |> filter(fn: (r) => r[\"finca\"] == \"${fincas}\")\n  |> filter(fn: (r) => r[\"id_sensor\"] == \"${sensor}\")\n  |> filter(fn: (r) => r[\"planta\"] == \"${cultivos}\")\n  |> filter(fn: (r) => r[\"usuario\"] == \"${usuarios}\")\n  |> group(columns: [\"_measurement\"], mode: \"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}